version: '2.4'
services: 
  nrf:
    build:
      context: .
      args:
        version: 3.0.5
    image: openverso/free5gs:3.0.5
    ports:
      - 8000:8000
    command: 
      - ./bin/nrf -nrfcfg config/nrfcfg.yaml
    restart : on-failure
  amf:
    build:
      context: .
      args:
        version: 3.0.5
    image: openverso/free5gs:3.0.5
    command: 
      - ./bin/amf -amfcfg config/amfcfg.yaml
    restart : on-failure
  smf:
    build:
      context: .
      args:
        version: 3.0.5
    image: openverso/free5gs:3.0.5
    command: 
      - ./bin/smf -smfcfg config/smfcfg.yaml
    restart : on-failure
  udr:
    build:
      context: .
      args:
        version: 3.0.5
    image: openverso/free5gs:3.0.5
    command: 
      - ./bin/udr -udrcfg config/udrcfg.yaml
    restart : on-failure
  pcf:
    build:
      context: .
      args:
        version: 3.0.5
    image: openverso/free5gs:3.0.5
    command: 
      - ./bin/pcf -pcfcfg config/pcfcfg.yaml
    restart : on-failure
  udm:
    build:
      context: .
      args:
        version: 3.0.5
    image: openverso/free5gs:3.0.5
    command: 
      - ./bin/udm -udmcfg config/udmcfg.yaml
    restart : on-failure
  nssf:
    build:
      context: .
      args:
        version: 3.0.5
    image: openverso/free5gs:3.0.5
    command: 
      - ./bin/nssf -nssfcfg config/nssfcfg.yaml
    restart : on-failure
  ausf:
    build:
      context: .
      args:
        version: 3.0.5
    image: openverso/free5gs:3.0.5
    command: 
      - ./bin/ausf -ausfcfg config/ausfcfg.yaml
    restart : on-failure
  upf:
    build:
      context: .
      args:
        version: 3.0.5
    cap_add:
      - NET_ADMIN
    image: openverso/free5gs:3.0.5
    command: 
      - ./bin/free5gc-upfd -f config/upfcfgb.yaml
    volumes:
      - ./config/upfcfgb.yaml:/free5gc/config/upfcfg.yaml
    restart : on-failure
  
  
