### For reference, see `open5gs.yaml`S

parameter:

mme:
    freeDiameter: mme.conf
    s1ap:
    gtpc:
    gummei: 
      plmn_id:
        mcc: "001"
        mnc: "01"
      mme_gid: 2
      mme_code: 1
    tai:
      plmn_id:
        mcc: "001"
        mnc: "01"
      tac: "0001"
    security:
        integrity_order : [ EIA1, EIA2, EIA0 ]
        ciphering_order : [ EEA0, EEA1, EEA2 ]
    network_name:
        full: Open5GS

sgw:
    gtpc:
      - name: sgw

pgw:
    gtpc:
      - name: pgw
