
parameter:

pgw:
  freeDiameter: pgw.conf
  gtpc:
    dev: eth0
  gtpu:
    dev: eth0
  ue_pool:
    - addr: 45.45.0.1/16
    #- addr: cafe::1/64
  dns:
    - 8.8.8.8
    - 8.8.4.4
    #- 2001:4860:4860::8888
    #- 2001:4860:4860::8844
  mtu: 1400

