version: '3'
services: 
  enodeb:
    build:
      context: ../../srs-lte/
      dockerfile: Dockerfile
    image: openverso/srs-lte:20_04_1
    command: 
      - enb
    privileged: true
    cap_add:
      - all
    environment:
      MME_HOSTNAME: mme
      ENB_HOSTNAME: enodeb
      UE_HOSTNAME: ue
      DEVICE_NAME: "zmq"
      DEVICE_ARGS: "fail_on_disconnect=true,tx_port=tcp://*:2000,rx_port=tcp://ue:2001,id=enb,base_srate=23.04e6"
  ue:
    build:
      context: ../../srs-lte/
      dockerfile: Dockerfile
    image: openverso/srs-lte:20_04_1
    command: 
      - ue
    privileged: true
    cap_add:
      - all
    environment:
      ENB_HOSTNAME: enodeb
      UE_HOSTNAME: ue
      DEVICE_NAME: "zmq"
      DEVICE_ARGS: "tx_port=tcp://*:2001,rx_port=tcp://enodeb:2000,id=ue,base_srate=23.04e6"
      MCC: "001"
      MNC: "01"
      MSISDN: "0000000001"
      KEY: "465B5CE8B199B49FAA5F0A2EE238A6BC"
      OPC: "E8ED289DEBA952E4283B54E88E6183CA"
