version: '3'
services: 
  enodeb:
    build:
      context: ../../srs-lte/
      dockerfile: Dockerfile
    image: openverso/srs-lte:20_10_1
    command: 
      - enb
    privileged: true
    cap_add:
      - all
    environment:
      MME_HOSTNAME: mme
      ENB_HOSTNAME: enodeb
      UE_HOSTNAME: ue
      MCC: "901"
      MNC: "70"

  ue:
    build:
      context: ../../srs-lte/
      dockerfile: Dockerfile
    image: openverso/srs-lte:20_10_1
    command: 
      - ue
    privileged: true
    cap_add:
      - all
    environment:
      ENB_HOSTNAME: enodeb
      UE_HOSTNAME: ue
      MCC: "901"
      MNC: "70"
      MSISDN: "0000000001"
      KEY: "465B5CE8B199B49FAA5F0A2EE238A6BC"
      OPC: "E8ED289DEBA952E4283B54E88E6183CA"
