### For reference, see `/opt/open5gs/etc/orig/open5gs/`
smf:
  info:
    - s_nssai:
      - sst: ${SST}
        sd: ${SD}
        dnn:
        - ${DNN}
  sbi:
    port: 7777
  gtpc:
  gtpu:
  pfcp:
  subnet:
    - addr: ${SUBNET_ADDR}
    #- addr: cafe::1/64
  dns:
    - 8.8.8.8
    - 8.8.4.4
    #- 2001:4860:4860::8888
    #- 2001:4860:4860::8844
  mtu: 1400
  freeDiameter: smf.conf

nrf:
  sbi:
    - name: nrf
      port: 7777
upf:
  pfcp:
    - name: ${UPF}

parameter:
max:
pool:
time: