### For reference, see `/opt/open5gs/etc/orig/open5gs/`
upf:
    pfcp:
    gtpu:
    subnet:
      - addr: ${SUBNET_ADDR}
        dnn: ${DNN}
      #- addr: cafe::1/64
smf:
#    pfcp:
#      - name: smf
parameter:
max:
pool: