version: '3'
services: 
  gnb1:
    build:
      context: ../../ueransim/
      dockerfile: Dockerfile
    image: openverso/ueransim:3.1.0
    container_name: gnb1
    command: 
      - gnb
    environment:
      AMF_HOSTNAME: amf
      GNB_HOSTNAME: gnb1
  ue1:
    build:
      context: ../../ueransim/
      dockerfile: Dockerfile
    image: openverso/ueransim:3.1.0
    container_name: ue1
    command: 
      - ue
    cap_add:
      - all
    privileged: true
    environment:
      GNB_HOSTNAME: gnb1
      APN: internet
      MSISDN: '0000000001'
