info:
  version: 1.0.1
  description: WebUI initial local configuration

configuration:
  mongodb: # the mongodb connected by this webui
    name: open5gs # name of the mongodb
    url: mongodb://mongo # a valid URL of the mongodb
