version: '3'
services: 
  gnb1:
    image: openverso/ueransim:3.1.6
    container_name: gnb1
    command: 
      - gnb
    environment:
      AMF_HOSTNAME: amf
      GNB_HOSTNAME: gnb1
  ue1:
    image: openverso/ueransim:3.1.6
    container_name: ue1
    command: 
      - ue
    cap_add:
      - all
    privileged: true
    environment:
      GNB_HOSTNAME: gnb1
      APN: internet
      MSISDN: '0000000001'
      KEY: '465B5CE8B199B49FAA5F0A2EE238A6BC'
      OP_TYPE: OPC
      OP: 'E8ED289DEBA952E4283B54E88E6183CA'
    
