version: '3'
services: 
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: open5gs
  amf:
    image: openverso/open5gs:2.2.3
    command: 
      - open5gs-amfd 
    restart : on-failure
  ausf:
    image: openverso/open5gs:2.2.3
    command: 
      - open5gs-ausfd
    restart : on-failure
  nrf:
    image: openverso/open5gs:2.2.3
    command: open5gs-nrfd   
    restart : on-failure 
    ports:
      - 7777:7777
  nssf:
    image: openverso/open5gs:2.2.3
    command: open5gs-nssfd   
    restart : on-failure 
  pcf:
    image: openverso/open5gs:2.2.3
    command: 
      - open5gs-pcfd
    environment:
      DB_URI: mongodb://mongo/open5gs
    restart : on-failure
  pcrf:
    image: openverso/open5gs:2.2.3
    command: ["open5gs-pcrfd"]
    environment:
      DB_URI: mongodb://mongo/open5gs
    restart: on-failure
  smf1:
    image: openverso/open5gs:2.2.3
    command: open5gs-smfd    
    restart : on-failure 
    environment:
      SST: 1
      SD: 000001
      UPF: upf1
      DNN: internet
      SUBNET_ADDR: 10.45.0.1/16
  smf2:
    image: openverso/open5gs:2.2.3
    command: open5gs-smfd    
    restart : on-failure 
    environment:
      SST: 1
      SD: 000002
      UPF: upf2
      DNN: movistar.es
      SUBNET_ADDR: 10.0.0.1/16
  udm:
    image: openverso/open5gs:2.2.3
    restart: on-failure
    command: 
      - open5gs-udmd
  udr:
    image: openverso/open5gs:2.2.3
    restart: on-failure
    environment:
      DB_URI: mongodb://mongo/open5gs
    command: 
      - open5gs-udrd
  upf1:
    container_name: upf1
    image: openverso/open5gs:2.2.3
    command:
      - open5gs-upfd
    cap_add:
      - all
    privileged: true
    restart: on-failure
    environment:
      SUBNET_ADDR: 10.45.0.1/16
      DNN: internet
  upf2:
    container_name: upf2
    image: openverso/open5gs:2.2.3
    command:
      - open5gs-upfd
    cap_add:
      - all
    privileged: true
    restart: on-failure
    environment:
      SUBNET_ADDR: 10.0.0.1/16
      DNN: movistar.es
  # upf2:
  #   container_name: upf2
  #   image: openverso/open5gs:2.2.3
  #   command:
  #     - open5gs-upfd
  #   cap_add:
  #     - all
  #   privileged: true
  #   restart: on-failure
  #   environment:
  #     SUBNET_ADDR: 10.0.0.1/16
  #     DNN: movistar.es
  webui:
    image: openverso/open5gs-webui:2.2.3  
    restart: on-failure
    environment:
      DB_URI: mongodb://mongo/open5gs
    ports:
      - 3000:3000
  portainer:
    image: portainer/portainer-ce
    ports:
    - 9000:9000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
