---
name: Test Pull Request

on: 
  pull_request:
    branches:
      - main
    paths:
      - 'images/**'
      - '!images/**/update_current_tag.sh'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: echo Hello World!
        run: |
          echo "Hello World!!!"
