name: push images

on:
  push:
    branches: [ main ]
env:
  default_branch: main

jobs:
  push:
    runs-on: [SI, standard]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed images
        id: list-changed
        run: |
          changed=$(git diff --name-only $default_branch -- $images_dir | cut -f1-2 -d'/' | uniq)
          echo "::set-output name=list_changed::$changed"
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: steps.list-changed.outputs.changed == 'true'

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        if: steps.list-changed.outputs.changed == 'true'

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}      

      - name: push changed images
        id: push
        run: |
            for image in $list_changed; do
              pushd $image
              make push
              popd
            done
        env:
          list_changed: ${{steps.list-changed.outputs.list_changed}}
        if: steps.list-changed.outputs.changed == 'true'